version: "3.8"

services:
  discord-bot:
    container_name: washington
    read_only: true
    build: .
    env_file: .env
    restart: any
    cpus: '0.5'
    mem_limit: 750M
    networks:
      - web

networks:
  web:
    name: washington_web
