version: "3.8"

services:
  discord-bot:
    container_name: washington
    read_only: true
    build: .
    env_file: .env
    restart: always
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 750M
    networks:
      - web

networks:
  web:
    name: washington_web
